### ISSUE TITLE
4 pishnehad

### ISSUE THREAD

**Issue by Yousha** [morrning/sarkesh#15]
1- Az " baraye simple-string ha estefade nakonid, bejash az ' estefade konid. Melse: echo "test", require("fmy_ile.php") va...
" baraye Variable-String hastesh va sor'atesh az ' kamtare.

2- Dar neveshtane dastoorate Language Constructs, az parantez estenade nakoid. Melse require_once, echo va...

3- Dar file import.sql niyazi be estefade az dastoorate ALTER nist, agar be in shekl jadval ro Create konid. Masalan:

create table `tbl_test`
(
	`i` smallint(5) unsigned not NULL auto_increment,
	`name` varchar(50) not NULL,
	primary key (`i`), <----------------------------------------
	unique index `tbl_test_name` (`name`), <------------
	index `tbl_test_state` (`state`) <------------------------
) engine = 'myisam' row_format = default auto_increment = 0 default character set = 'utf8' collate = 'utf8_general_ci';

4- Hamchenin az dastoore PRINT dar safehate WEB estefade nakonid. In dastoor baraye Console/CLI tarahi shode.
Google konid: php echo vs print

**Comment by Yousha** [comment]
Hamchenin az dastoore PRINT dar safehate WEB estefade nakonid. In dastoor baraye Console/CLI tarahi shode.
Google konid: php echo vs print

**Comment by morrning** [comment]
مرسی از راهنماییهاتون . سعی میکنم در آینده اعمال کنم. البته فقط اون آلتر در اس کیو ال  رو نمیدونستم.
همچنین اینکه برای گزارش باگ ها روی گروه در آدرس زیر درخواست بفرستید
https://github.com/sarkeshLtd/sarkesh
که فورک اصلی هست.
